import type { PropType } from 'vue'
import type { CalendarDisplayFormatter, CalendarModelValue } from './types'
import { calendarProps } from 'vant'

export const calendarWrapperProps = {
  type: calendarProps.type,
  switchMode: calendarProps.switchMode,
  title: calendarProps.title,
  color: calendarProps.color,
  round: calendarProps.round,
  readonly: calendarProps.readonly,
  maxRange: calendarProps.maxRange,
  position: calendarProps.position,
  teleport: calendarProps.teleport,
  showMark: calendarProps.showMark,
  showTitle: calendarProps.showTitle,
  formatter: calendarProps.formatter,
  rowHeight: calendarProps.rowHeight,
  confirmText: calendarProps.confirmText,
  rangePrompt: calendarProps.rangePrompt,
  lazyRender: calendarProps.lazyRender,
  showConfirm: calendarProps.showConfirm,
  defaultDate: calendarProps.defaultDate,
  allowSameDay: calendarProps.allowSameDay,
  showSubtitle: calendarProps.showSubtitle,
  closeOnPopstate: calendarProps.closeOnPopstate,
  showRangePrompt: calendarProps.showRangePrompt,
  confirmDisabledText: calendarProps.confirmDisabledText,
  closeOnClickOverlay: calendarProps.closeOnClickOverlay,
  safeAreaInsetTop: calendarProps.safeAreaInsetTop,
  safeAreaInsetBottom: calendarProps.safeAreaInsetBottom,
  minDate: calendarProps.minDate,
  maxDate: calendarProps.maxDate,
  firstDayOfWeek: calendarProps.firstDayOfWeek,
  modelValue: {
    type: [Date, Array] as PropType<CalendarModelValue>,
    default: undefined,
  },
  placeholder: String,
  displayFormatter: Function as PropType<CalendarDisplayFormatter>,
  disabled: Boolean,
} as const
